name: po_example
description: An example for illustrating pub outdated

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.4.4
  http: ^0.11.0
  path: ^1.5.0
  terminal_tools:
    path: ./pkg/terminal_tools/

dev_dependencies:
  pedantic: ^1.9.0
